[project]
name = "neorl"
version = "0.1.3"
description = ""
authors = [
    {name = "bitsandscraps",email = "17763502+bitsandscraps@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy (>=2.4.4,<3.0.0)",
    "pandas (>=3.0.2,<4.0.0)",
    "setuptools",
    "gymnasium (>=1.2.3,<2.0.0)",
    "gymnasium-robotics[mujoco-py] (>=1.4.2,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.setuptools.package-data]
neorl = [
    'neorl_envs/finance/trade.csv',
    'neorl_envs/finance/train.csv',
    'neorl_envs/citylearn/data/*',
    'neorl_envs/citylearn/data/Climate_Zone_1/*',
    'neorl_envs/citylearn/data/Climate_Zone_2/*',
    'neorl_envs/citylearn/data/Climate_Zone_3/*',
    'neorl_envs/citylearn/data/Climate_Zone_4/*',
    'neorl_envs/citylearn/data/Climate_Zone_5/*',
    'data_map.json'
]


